spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tododb}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:todouser}
    password: ${DB_PASSWORD:todopass}
  sql:
    init:
      mode: never